### ISSUE TITLE
Cover Image not displayed

### ISSUE THREAD

**Issue by lucifermorningstar1305** [AbdelrhmanNile/steal#12]
After launching steal from the command line, the application starts up, but the game's cover image is not displayed.  Here's a screenshot for your reference.
![Screenshot_4](https://user-images.githubusercontent.com/17244142/176662648-6a4f2e3d-9685-441c-b3bd-a34483784679.png)

And here's the error log:
```
 --- Logging error ---
 Traceback (most recent call last):
   File "/home/bvkng/miniconda3/lib/python3.9/site-packages/kivy/loader.py", line 345, in _load_urllib
     fd = opener.open(request)
   File "/home/bvkng/miniconda3/lib/python3.9/urllib/request.py", line 523, in open
     response = meth(req, response)
   File "/home/bvkng/miniconda3/lib/python3.9/urllib/request.py", line 632, in http_response
     response = self.parent.error(
   File "/home/bvkng/miniconda3/lib/python3.9/urllib/request.py", line 561, in error
     return self._call_chain(*args)
   File "/home/bvkng/miniconda3/lib/python3.9/urllib/request.py", line 494, in _call_chain
     result = func(*args)
   File "/home/bvkng/miniconda3/lib/python3.9/urllib/request.py", line 641, in http_error_default
     raise HTTPError(req.full_url, code, msg, hdrs, fp)
 urllib.error.HTTPError: HTTP Error 403: Forbidden
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/home/bvkng/miniconda3/lib/python3.9/logging/__init__.py", line 1083, in emit
     msg = self.format(record)
   File "/home/bvkng/miniconda3/lib/python3.9/logging/__init__.py", line 927, in format
     return fmt.format(record)
   File "/home/bvkng/miniconda3/lib/python3.9/site-packages/kivy/logger.py", line 291, in format
     record = copy.deepcopy(record)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 172, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 270, in _reconstruct
     state = deepcopy(state, memo)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 146, in deepcopy
     y = copier(x, memo)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 230, in _deepcopy_dict
     y[deepcopy(key, memo)] = deepcopy(value, memo)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 146, in deepcopy
     y = copier(x, memo)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 210, in _deepcopy_tuple
     y = [deepcopy(a, memo) for a in x]
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 210, in <listcomp>
     y = [deepcopy(a, memo) for a in x]
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 172, in deepcopy
     y = _reconstruct(x, memo, *rv)
   File "/home/bvkng/miniconda3/lib/python3.9/copy.py", line 264, in _reconstruct
     y = func(*args)
 TypeError: __init__() missing 5 required positional arguments: 'url', 'code', 'msg', 'hdrs', and 'fp'
 Call stack:
   File "/home/bvkng/miniconda3/lib/python3.9/threading.py", line 930, in _bootstrap
     self._bootstrap_inner()
   File "/home/bvkng/miniconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
     self.run()
   File "/home/bvkng/miniconda3/lib/python3.9/site-packages/kivy/loader.py", line 533, in run
     func(*args, **kargs)
   File "/home/bvkng/miniconda3/lib/python3.9/site-packages/kivy/loader.py", line 290, in _load
     data = self._load_urllib(filename, kwargs['kwargs'])
   File "/home/bvkng/miniconda3/lib/python3.9/site-packages/kivy/loader.py", line 382, in _load_urllib
     Logger.exception('Loader: Failed to load image <%s>' % filename)
 Message: 'Loader: Failed to load image <https://images.igdb.com/igdb/image/upload/t_1080p/co2sk0.jpg>'
 Arguments: ()

```

**Comment by AbdelrhmanNile** [comment]
strange, can you open https://images.igdb.com/igdb/image/upload/t_1080p/co2sk0.jpg in your browser and see if it loads?

**Comment by AbdelrhmanNile** [comment]
steaL uses johncena141 repacks, games run in pre-configured wine prefixes by them, i guess you can install whatever you want in a game's wine prefix, for any games-related support thing please contact [johncena141 on their matrix server](https://matrix.to/#/#rumpowered:matrix.org)
