### ISSUE TITLE
Permission error on startup?

### ISSUE THREAD

**Issue by VinnyStalck** [AbdelrhmanNile/steal#35]
A transparent window open and close quickly, showing a permission denied message in the log
Process doesn't close  

Using nobara/fedora 

<details>
<summary>Log</summary>

```
[INFO   ] [Logger      ] Record log in /home/stalck/.kivy/logs/kivy_23-03-19_9.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/home/stalck/.local/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.10 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 520.61.05'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1650/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
 Traceback (most recent call last):
   File "/tmp/steal/main.py", line 557, in <module>
     app.run()
   File "/home/stalck/.local/lib/python3.10/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/home/stalck/.local/lib/python3.10/site-packages/kivy/app.py", line 924, in _run_prepare
     root = self.build()
   File "/tmp/steal/main.py", line 509, in build
     threading.Thread(target=self.init_steal, name="init_steal").run()
   File "/usr/lib64/python3.10/threading.py", line 953, in run
     self._target(*self._args, **self._kwargs)
   File "/tmp/steal/main.py", line 525, in init_steal
     self.check_conf()
   File "/tmp/steal/main.py", line 539, in check_conf
     os.makedirs(self.steal_path)  # make it
   File "/usr/lib64/python3.10/os.py", line 215, in makedirs
     makedirs(head, exist_ok=exist_ok)
   File "/usr/lib64/python3.10/os.py", line 215, in makedirs
     makedirs(head, exist_ok=exist_ok)
   File "/usr/lib64/python3.10/os.py", line 225, in makedirs
     mkdir(name, mode)
 PermissionError: [Errno 13] Permission denied: '/home/Stalck'
```

</details>

**Comment by AbdelrhmanNile** [comment]
@VinnyStalck 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
