### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ArnoldLaynee** [AbdelrhmanNile/steal#42]
` Traceback (most recent call last):
   File "/tmp/steal/main.py", line 557, in <module>
     app.run()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/usr/lib/python3/dist-packages/kivy/app.py", line 924, in _run_prepare
     root = self.build()
   File "/tmp/steal/main.py", line 509, in build
     threading.Thread(target=self.init_steal, name="init_steal").run()
   File "/usr/lib/python3.10/threading.py", line 953, in run
     self._target(*self._args, **self._kwargs)
   File "/tmp/steal/main.py", line 521, in init_steal
     self.usr = os.getlogin()
 OSError: [Errno 6] No such device or address
`

On linux mint built from source made sure i installed everything needed a transparent window opens and closes idk if it makes any difference but i use i3

**Comment by AbdelrhmanNile** [comment]
@ArnoldLaynee 
checkout the new version!
https://github.com/AbdelrhmanNile/UnderTaker141
